### ISSUE TITLE
Implode argument order

### ISSUE THREAD

**Issue by shakethatweight-simon** [helgatheviking/wc-mnm-grouped#3]
PHP8.x no longer support the option to specify arguments in either order, it is now strictly separator and then array:

https://github.com/kathyisawesome/wc-mnm-grouped/blob/5690251d969e6f2247f0fa651af87a9182bfb4f4/wc-mnm-grouped.php#L257

https://www.php.net/implode

```
implode(string $separator, array $array): string

Alternative signature (not supported with named arguments):
implode(array $array): string

Legacy signature (deprecated as of PHP 7.4.0, removed as of PHP 8.0.0):
implode(array $array, string $separator): string
```

**Comment by helgatheviking** [comment]
So the two args beef to be inverted? That was probably a mistake in the first place. Thanks for reporting.

**Comment by shakethatweight-simon** [comment]
It's a very common mistake, so much that its been mentioned in the documentation for nearly 18 years, I'm sure I'll find it in my code too. https://web.archive.org/web/20031127041103/http://us2.php.net/implode
